name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: setup_boost
      run: apt-get install libboost-all-dev
    
    - name: GivePermisson
      run: chmod +x ./linux_setup.sh
    
    - name: configure
      run: ./linux_setup.sh
      
    - name: make
      run: make
